image: docker:latest

variables:
  GIT_DEPTH: "3"
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - echo $CI_COMMIT_REF_NAME

docker-build test:
  stage: build
  allow_failure: false
  script:
    - docker build --pull -t $CI_COMMIT_REF_NAME .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker image tag $CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - branches
  when: manual

docker-build prod:
  stage: build
  allow_failure: false
  script:
    - docker build --pull -t $CI_COMMIT_REF_NAME .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker image tag $CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - tags
  when: manual
  
push-docker-hub:
  stage: build
  allow_failure: false
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME n0r1skcom/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWD
    - docker plugin push n0r1skcom/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
  when: manual
